#pragma once

enum class DualSenseControllerState {
    DISCONNECTED,
    CONNECTED
};

enum class DualSenseControllerValueId {
    DUALSENSE_BUTTON_X = 0,
    DUALSENSE_BUTTON_CIRCLE,
    DUALSENSE_BUTTON_SQUARE,
    DUALSENSE_BUTTON_TRIANGLE,
    DUALSENSE_BUTTON_L1,
    DUALSENSE_BUTTON_R1,
    DUALSENSE_BUTTON_L2,
    DUALSENSE_BUTTON_R2,
    DUALSENSE_BUTTON_SHARE,
    DUALSENSE_BUTTON_OPTIONS,
    DUALSENSE_BUTTON_L3,
    DUALSENSE_BUTTON_R3,
    DUALSENSE_BUTTON_PS,
    DUALSENSE_BUTTON_TOUCHPAD,
    DUALSENSE_AXIS_LEFT_X,
    DUALSENSE_AXIS_LEFT_Y,
    DUALSENSE_AXIS_RIGHT_X,
    DUALSENSE_AXIS_RIGHT_Y,
    DUALSENSE_TRIGGER_LEFT,
    DUALSENSE_TRIGGER_RIGHT
    // Add more if needed
};
